export const BOOK_ACTION_CONSTANTS = { 
    ADD_INITIAL_BOOK_ENTRY: 'ADD_INITIAL_BOOK_ENTRY',
    UPDATE_BOOK_ENTRY: 'UPDATE_BOOK_ENTRY'
};

export const LOCAL_STORAGE_KEY = 'bookData';

export const BOOK_TYPES = {
    BOOK_BIDS: 'BOOK_BIDS',
    BOOK_ASKS: 'BOOK_ASKS',
};

export const FLOAT_PRECISION_LENGTH = 4;

export const SETTINGS_MODAL_CONSTANTS = {
    SHOW_MODAL: 'SHOW_MODAL',
    HIDE_MODAL: 'HIDE_MODAL'
}

export const BOOK_VISUAL_SETTING_CONSTANTS = {
    SHOW_CUMULATIVE: 'SHOW_CUMULATIVE',
    SHOW_AMOUNT: 'SHOW_AMOUNT'
}
